//! Private implementation modules for the engine's archive adapters.

#[path = "apple_archive_backend.rs"]
pub mod apple_archive_backend;
#[path = "apple_dmg_backend.rs"]
pub mod apple_dmg_backend;
#[path = "apple_pkg_backend.rs"]
pub mod apple_pkg_backend;
#[path = "ar_backend.rs"]
pub mod ar_backend;
#[path = "cab_backend.rs"]
pub mod cab_backend;
#[path = "cpio_backend.rs"]
pub mod cpio_backend;
#[path = "deb_backend.rs"]
pub mod deb_backend;
#[path = "lha_backend.rs"]
pub mod lha_backend;
#[path = "lzop_decoder.rs"]
pub mod lzop_decoder;
#[path = "msi_backend.rs"]
pub mod msi_backend;
#[path = "mtree_backend.rs"]
pub mod mtree_backend;
#[path = "rar_backend.rs"]
pub mod rar_backend;
#[path = "raw_stream_backend.rs"]
pub mod raw_stream_backend;
#[path = "rpm_backend.rs"]
pub mod rpm_backend;
#[path = "sevenz_backend.rs"]
pub mod sevenz_backend;
#[path = "squashfs_backend.rs"]
pub mod squashfs_backend;
#[path = "tar_backend.rs"]
pub mod tar_backend;
#[path = "tar_gz_backend.rs"]
pub mod tar_gz_backend;
#[path = "tar_zst_backend.rs"]
pub mod tar_zst_backend;
#[path = "unix_compress_decoder.rs"]
pub mod unix_compress_decoder;
#[path = "uu_decoder.rs"]
pub mod uu_decoder;
#[path = "virtual_disk_backend.rs"]
pub mod virtual_disk_backend;
#[path = "warc_backend.rs"]
pub mod warc_backend;
#[path = "wim_backend.rs"]
pub mod wim_backend;
#[path = "xar_backend.rs"]
pub mod xar_backend;
#[path = "zip_backend.rs"]
pub mod zip_backend;
