//! ECDSA P-256 SHA-256 primitive helpers.

use openssl::bn::{BigNum, BigNumContext, BigNumRef};
use openssl::ec::EcKey;
use openssl::ecdsa::EcdsaSig;
use openssl::error::ErrorStack;
use openssl::nid::Nid;
use openssl::pkey::{HasPublic, PKey, Private, Public};
use sha2::{Digest, Sha256};

/// Nonce strategy used by this module.
pub const P256_NONCE_MODE: NonceMode = NonceMode::ProviderCsprng;

/// Supported nonce modes for this helper module.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum NonceMode {
    /// RFC 6979 deterministic nonce generation.
    Rfc6979,
    /// Provider-backed CSPRNG nonce generation.
    ///
    /// OpenSSL does not expose RFC 6979 selection for this API path in our
    /// current dependency stack, so signer nonces are generated by the provider
    /// RNG-backed implementation.
    ProviderCsprng,
}

/// Fixed-width signature length for P-1363 `(r || s)` on P-256.
pub const P256_P1363_SIGNATURE_LENGTH: usize = 64;
const P256_COORDINATE_LENGTH: usize = 32;

/// Errors returned by the P-256 helpers.
#[derive(Debug)]
pub enum P256SignatureError {
    /// Signature input is not exactly 64 bytes.
    InvalidSignatureLength { actual: usize },
    /// Signature rejected because `s` is not canonical low-S.
    NonCanonicalLowS,
    /// Unexpected curve for the provided key.
    UnsupportedCurve,
    /// OpenSSL rejected an operation.
    Crypto(ErrorStack),
}

impl From<ErrorStack> for P256SignatureError {
    fn from(err: ErrorStack) -> Self {
        Self::Crypto(err)
    }
}

/// Signs `payload` bytes with SHA-256 + P-256 and returns fixed-width P-1363 bytes.
///
/// The SHA-256 hashing step is intentionally inside this helper to avoid callers
/// accidentally hashing payloads twice.
pub fn sign_p256_sha256_p1363(
    private_key: &PKey<Private>,
    payload: &[u8],
) -> Result<[u8; P256_P1363_SIGNATURE_LENGTH], P256SignatureError> {
    let private_key = private_key.ec_key()?;
    ensure_p256_key(&private_key)?;

    let digest = sha256_digest(payload);
    let signature = EcdsaSig::sign(&digest, &private_key)?;

    let (order, half_order) = curve_orders(&private_key)?;
    let s = normalize_low_s(signature.s(), &order, &half_order)?;

    let mut out = [0_u8; P256_P1363_SIGNATURE_LENGTH];
    out[..P256_COORDINATE_LENGTH]
        .copy_from_slice(&signature.r().to_vec_padded(P256_COORDINATE_LENGTH as i32)?);
    out[P256_COORDINATE_LENGTH..].copy_from_slice(&s.to_vec_padded(P256_COORDINATE_LENGTH as i32)?);
    Ok(out)
}

/// Verifies a SHA-256 + P-256 P-1363 signature.
///
/// The SHA-256 hashing step is intentionally inside this helper to avoid callers
/// accidentally hashing payloads twice.
pub fn verify_p256_sha256_p1363(
    public_key: &PKey<Public>,
    payload: &[u8],
    signature: &[u8],
) -> Result<bool, P256SignatureError> {
    let public_key = public_key.ec_key()?;
    ensure_p256_key(&public_key)?;

    let (order, half_order) = curve_orders(&public_key)?;
    let signature = decode_p1363_signature(signature)?;

    if !is_low_s(signature.s(), &order, &half_order)? {
        return Err(P256SignatureError::NonCanonicalLowS);
    }

    let digest = sha256_digest(payload);
    Ok(signature.verify(&digest, &public_key)?)
}

fn sha256_digest(payload: &[u8]) -> [u8; 32] {
    Sha256::digest(payload).into()
}

fn ensure_p256_key<T: HasPublic>(key: &EcKey<T>) -> Result<(), P256SignatureError> {
    let curve = key.group().curve_name().ok_or(P256SignatureError::UnsupportedCurve)?;
    if curve == Nid::X9_62_PRIME256V1 {
        Ok(())
    } else {
        Err(P256SignatureError::UnsupportedCurve)
    }
}

fn curve_orders<T: HasPublic>(key: &EcKey<T>) -> Result<(BigNum, BigNum), P256SignatureError> {
    let mut order = BigNum::new()?;
    let mut half_order = BigNum::new()?;
    let mut context = BigNumContext::new()?;
    key.group().order(&mut order, &mut context)?;
    half_order.copy_from(&order)?;
    half_order.rshift1(&order)?;
    Ok((order, half_order))
}

fn normalize_low_s(
    s: &BigNumRef,
    order: &BigNumRef,
    half_order: &BigNumRef,
) -> Result<BigNum, P256SignatureError> {
    if is_low_s(s, &order, &half_order)? {
        Ok(s.to_owned()?)
    } else {
        let mut normalized = order.to_owned()?;
        normalized.checked_sub(order, s)?;
        Ok(normalized)
    }
}

fn is_low_s(s: &BigNumRef, order: &BigNumRef, half_order: &BigNumRef) -> Result<bool, ErrorStack> {
    if s.ucmp(order) != std::cmp::Ordering::Less {
        return Ok(false);
    }

    Ok(matches!(s.ucmp(half_order), std::cmp::Ordering::Less | std::cmp::Ordering::Equal))
}

fn decode_p1363_signature(signature: &[u8]) -> Result<EcdsaSig, P256SignatureError> {
    if signature.len() != P256_P1363_SIGNATURE_LENGTH {
        return Err(P256SignatureError::InvalidSignatureLength {
            actual: signature.len(),
        });
    }

    let r = BigNum::from_slice(&signature[..P256_COORDINATE_LENGTH])?;
    let s = BigNum::from_slice(&signature[P256_COORDINATE_LENGTH..])?;
    Ok(EcdsaSig::from_private_components(r, s)?)
}

#[cfg(test)]
mod tests {
    use super::{
        curve_orders, sign_p256_sha256_p1363, verify_p256_sha256_p1363, NonceMode, P256_NONCE_MODE,
        P256_P1363_SIGNATURE_LENGTH,
    };
    use openssl::bn::BigNum;
    use openssl::ec::EcGroup;
    use openssl::ec::EcKey;
    use openssl::nid::Nid;
    use openssl::pkey::{PKey, Private, Public};
    use super::P256SignatureError;

    fn test_keys() -> Result<(PKey<Private>, PKey<Public>), openssl::error::ErrorStack> {
        let group = EcGroup::from_curve_name(Nid::X9_62_PRIME256V1)?;
        let private = EcKey::generate(&group)?;
        let public = EcKey::from_public_key(&group, private.public_key())?;
        Ok((PKey::from_ec_key(private)?, PKey::from_ec_key(public)?))
    }

    #[test]
    fn p256_signature_is_64_bytes_and_rejects_wrong_key_or_tamper() -> Result<(), P256SignatureError> {
        let (private, public) = test_keys()?;
        let payload = b"deterministic payload";

        let signature = sign_p256_sha256_p1363(&private, payload)?;
        assert_eq!(signature.len(), P256_P1363_SIGNATURE_LENGTH);

        assert!(verify_p256_sha256_p1363(&public, payload, &signature)?);

        let tampered_payload = b"tampered payload";
        assert!(!verify_p256_sha256_p1363(&public, tampered_payload, &signature)?);

        let (_other_private, other_public) = test_keys()?;
        assert!(!verify_p256_sha256_p1363(&other_public, payload, &signature)?);

        Ok(())
    }

    #[test]
    fn p256_signature_nonce_path_matches_documented_mode() -> Result<(), P256SignatureError> {
        let (private, _public) = test_keys()?;
        let payload = b"nonce check payload";

        let first = sign_p256_sha256_p1363(&private, payload)?;
        let second = sign_p256_sha256_p1363(&private, payload)?;

        match P256_NONCE_MODE {
            NonceMode::Rfc6979 => assert_eq!(first, second),
            NonceMode::ProviderCsprng => assert_ne!(first, second),
        }

        Ok(())
    }

    #[test]
    fn p256_verification_rejects_high_s_signature() -> Result<(), P256SignatureError> {
        let (private, public) = test_keys()?;
        let payload = b"high-s check payload";

        let signature = sign_p256_sha256_p1363(&private, payload)?;

        let ec_private = private.ec_key()?;
        let (_order, mut half_order) = curve_orders(&ec_private)?;
        let mut one = BigNum::from_u32(1)?;
        half_order.checked_add(&half_order, &one)?;
        let mut high_signature = signature;
        high_signature[P256_P1363_SIGNATURE_LENGTH / 2..]
            .copy_from_slice(&half_order.to_vec_padded(32)?);

        let result = verify_p256_sha256_p1363(&public, payload, &high_signature);
        assert!(matches!(result, Err(P256SignatureError::NonCanonicalLowS)));

        Ok(())
    }

    #[test]
    fn p256_helpers_reject_non_p256_keys() {
        let group = EcGroup::from_curve_name(Nid::SECP384R1).unwrap();
        let private = EcKey::generate(&group).unwrap();
        let public = EcKey::from_public_key(&group, private.public_key()).unwrap();
        let private_key = PKey::from_ec_key(private).unwrap();
        let public_key = PKey::from_ec_key(public).unwrap();

        let signature = [0_u8; P256_P1363_SIGNATURE_LENGTH];
        assert!(matches!(
            super::verify_p256_sha256_p1363(&private_key, b"payload", &signature),
            Err(P256SignatureError::UnsupportedCurve)
        ));
        assert!(matches!(
            super::verify_p256_sha256_p1363(&public_key, b"payload", &signature),
            Err(P256SignatureError::UnsupportedCurve)
        ));
    }
}
