[package]
name = "zmanager-cli"
version.workspace = true
description = "Command-line archive manager powered by zmanager-core."
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
build = "build.rs"

[[bin]]
name = "zmanager-cli"
path = "src/main.rs"

[[bin]]
name = "zm"
path = "src/bin/zm.rs"

[dependencies]
anstream = "1.0.0"
anstyle = "1.0.14"
reqwest = { version = "0.12.28", features = ["blocking", "json"] }
rpassword = "7.5.2"
serde_json = "1.0.140"
zmanager-core = { path = "../zmanager-core", version = "2.0.0" }

[dev-dependencies]
flate2 = "1.1.9"
sha2 = "0.10.9"
tar = "0.4.45"
zip = "8.6.0"
zstd = "0.13.3"

[target.'cfg(unix)'.dev-dependencies]
libc = "0.2"
xattr = "1.6.1"

[target.'cfg(windows)'.dev-dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Ioctl",
    "Win32_System_Threading",
] }

[lints]
workspace = true
