// Pre-generated libarchive bindings for linux-musl targets.
//
// bindgen dlopens libclang while generating bindings, which a static-musl
// build host (the Alpine packaging container) cannot do, so these bindings
// are checked in and used by build.rs whenever CARGO_CFG_TARGET_ENV is musl.
// Regenerate with the same builder used in build.rs::generate_bindings
// (wrapper.h + allowlists + `-fsigned-char`) on a linux host, e.g. inside
// `docker run --rm --platform linux/arm64 -v "$PWD:/ws" rust:1` after
// `apt-get install clang libclang-dev`.
//
/* automatically generated by rust-bindgen 0.70.1 */

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        let bit_index = if cfg!(target_endian = "big") { 7 - (index % 8) } else { index % 8 };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        let bit_index = if cfg!(target_endian = "big") { 7 - (index % 8) } else { index % 8 };
        let mask = 1 << bit_index;
        if val {
            *byte |= mask;
        } else {
            *byte &= !mask;
        }
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") { bit_width as usize - 1 - i } else { i };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") { bit_width as usize - 1 - i } else { i };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
}
pub const ARCHIVE_VERSION_NUMBER: u32 = 3008009;
pub const ARCHIVE_VERSION_ONLY_STRING: &[u8; 6] = b"3.8.9\0";
pub const ARCHIVE_VERSION_STRING: &[u8; 17] = b"libarchive 3.8.9\0";
pub const ARCHIVE_EOF: u32 = 1;
pub const ARCHIVE_OK: u32 = 0;
pub const ARCHIVE_RETRY: i32 = -10;
pub const ARCHIVE_WARN: i32 = -20;
pub const ARCHIVE_FAILED: i32 = -25;
pub const ARCHIVE_FATAL: i32 = -30;
pub const ARCHIVE_FILTER_NONE: u32 = 0;
pub const ARCHIVE_FILTER_GZIP: u32 = 1;
pub const ARCHIVE_FILTER_BZIP2: u32 = 2;
pub const ARCHIVE_FILTER_COMPRESS: u32 = 3;
pub const ARCHIVE_FILTER_PROGRAM: u32 = 4;
pub const ARCHIVE_FILTER_LZMA: u32 = 5;
pub const ARCHIVE_FILTER_XZ: u32 = 6;
pub const ARCHIVE_FILTER_UU: u32 = 7;
pub const ARCHIVE_FILTER_RPM: u32 = 8;
pub const ARCHIVE_FILTER_LZIP: u32 = 9;
pub const ARCHIVE_FILTER_LRZIP: u32 = 10;
pub const ARCHIVE_FILTER_LZOP: u32 = 11;
pub const ARCHIVE_FILTER_GRZIP: u32 = 12;
pub const ARCHIVE_FILTER_LZ4: u32 = 13;
pub const ARCHIVE_FILTER_ZSTD: u32 = 14;
pub const ARCHIVE_COMPRESSION_NONE: u32 = 0;
pub const ARCHIVE_COMPRESSION_GZIP: u32 = 1;
pub const ARCHIVE_COMPRESSION_BZIP2: u32 = 2;
pub const ARCHIVE_COMPRESSION_COMPRESS: u32 = 3;
pub const ARCHIVE_COMPRESSION_PROGRAM: u32 = 4;
pub const ARCHIVE_COMPRESSION_LZMA: u32 = 5;
pub const ARCHIVE_COMPRESSION_XZ: u32 = 6;
pub const ARCHIVE_COMPRESSION_UU: u32 = 7;
pub const ARCHIVE_COMPRESSION_RPM: u32 = 8;
pub const ARCHIVE_COMPRESSION_LZIP: u32 = 9;
pub const ARCHIVE_COMPRESSION_LRZIP: u32 = 10;
pub const ARCHIVE_FORMAT_BASE_MASK: u32 = 16711680;
pub const ARCHIVE_FORMAT_CPIO: u32 = 65536;
pub const ARCHIVE_FORMAT_CPIO_POSIX: u32 = 65537;
pub const ARCHIVE_FORMAT_CPIO_BIN_LE: u32 = 65538;
pub const ARCHIVE_FORMAT_CPIO_BIN_BE: u32 = 65539;
pub const ARCHIVE_FORMAT_CPIO_SVR4_NOCRC: u32 = 65540;
pub const ARCHIVE_FORMAT_CPIO_SVR4_CRC: u32 = 65541;
pub const ARCHIVE_FORMAT_CPIO_AFIO_LARGE: u32 = 65542;
pub const ARCHIVE_FORMAT_CPIO_PWB: u32 = 65543;
pub const ARCHIVE_FORMAT_SHAR: u32 = 131072;
pub const ARCHIVE_FORMAT_SHAR_BASE: u32 = 131073;
pub const ARCHIVE_FORMAT_SHAR_DUMP: u32 = 131074;
pub const ARCHIVE_FORMAT_TAR: u32 = 196608;
pub const ARCHIVE_FORMAT_TAR_USTAR: u32 = 196609;
pub const ARCHIVE_FORMAT_TAR_PAX_INTERCHANGE: u32 = 196610;
pub const ARCHIVE_FORMAT_TAR_PAX_RESTRICTED: u32 = 196611;
pub const ARCHIVE_FORMAT_TAR_GNUTAR: u32 = 196612;
pub const ARCHIVE_FORMAT_ISO9660: u32 = 262144;
pub const ARCHIVE_FORMAT_ISO9660_ROCKRIDGE: u32 = 262145;
pub const ARCHIVE_FORMAT_ZIP: u32 = 327680;
pub const ARCHIVE_FORMAT_EMPTY: u32 = 393216;
pub const ARCHIVE_FORMAT_AR: u32 = 458752;
pub const ARCHIVE_FORMAT_AR_GNU: u32 = 458753;
pub const ARCHIVE_FORMAT_AR_BSD: u32 = 458754;
pub const ARCHIVE_FORMAT_MTREE: u32 = 524288;
pub const ARCHIVE_FORMAT_RAW: u32 = 589824;
pub const ARCHIVE_FORMAT_XAR: u32 = 655360;
pub const ARCHIVE_FORMAT_LHA: u32 = 720896;
pub const ARCHIVE_FORMAT_CAB: u32 = 786432;
pub const ARCHIVE_FORMAT_RAR: u32 = 851968;
pub const ARCHIVE_FORMAT_7ZIP: u32 = 917504;
pub const ARCHIVE_FORMAT_WARC: u32 = 983040;
pub const ARCHIVE_FORMAT_RAR_V5: u32 = 1048576;
pub const ARCHIVE_READ_FORMAT_CAPS_NONE: u32 = 0;
pub const ARCHIVE_READ_FORMAT_CAPS_ENCRYPT_DATA: u32 = 1;
pub const ARCHIVE_READ_FORMAT_CAPS_ENCRYPT_METADATA: u32 = 2;
pub const ARCHIVE_READ_FORMAT_ENCRYPTION_UNSUPPORTED: i32 = -2;
pub const ARCHIVE_READ_FORMAT_ENCRYPTION_DONT_KNOW: i32 = -1;
pub const ARCHIVE_EXTRACT_OWNER: u32 = 1;
pub const ARCHIVE_EXTRACT_PERM: u32 = 2;
pub const ARCHIVE_EXTRACT_TIME: u32 = 4;
pub const ARCHIVE_EXTRACT_NO_OVERWRITE: u32 = 8;
pub const ARCHIVE_EXTRACT_UNLINK: u32 = 16;
pub const ARCHIVE_EXTRACT_ACL: u32 = 32;
pub const ARCHIVE_EXTRACT_FFLAGS: u32 = 64;
pub const ARCHIVE_EXTRACT_XATTR: u32 = 128;
pub const ARCHIVE_EXTRACT_SECURE_SYMLINKS: u32 = 256;
pub const ARCHIVE_EXTRACT_SECURE_NODOTDOT: u32 = 512;
pub const ARCHIVE_EXTRACT_NO_AUTODIR: u32 = 1024;
pub const ARCHIVE_EXTRACT_NO_OVERWRITE_NEWER: u32 = 2048;
pub const ARCHIVE_EXTRACT_SPARSE: u32 = 4096;
pub const ARCHIVE_EXTRACT_MAC_METADATA: u32 = 8192;
pub const ARCHIVE_EXTRACT_NO_HFS_COMPRESSION: u32 = 16384;
pub const ARCHIVE_EXTRACT_HFS_COMPRESSION_FORCED: u32 = 32768;
pub const ARCHIVE_EXTRACT_SECURE_NOABSOLUTEPATHS: u32 = 65536;
pub const ARCHIVE_EXTRACT_CLEAR_NOCHANGE_FFLAGS: u32 = 131072;
pub const ARCHIVE_EXTRACT_SAFE_WRITES: u32 = 262144;
pub const ARCHIVE_READDISK_RESTORE_ATIME: u32 = 1;
pub const ARCHIVE_READDISK_HONOR_NODUMP: u32 = 2;
pub const ARCHIVE_READDISK_MAC_COPYFILE: u32 = 4;
pub const ARCHIVE_READDISK_NO_TRAVERSE_MOUNTS: u32 = 8;
pub const ARCHIVE_READDISK_NO_XATTR: u32 = 16;
pub const ARCHIVE_READDISK_NO_ACL: u32 = 32;
pub const ARCHIVE_READDISK_NO_FFLAGS: u32 = 64;
pub const ARCHIVE_READDISK_NO_SPARSE: u32 = 128;
pub const ARCHIVE_MATCH_MTIME: u32 = 256;
pub const ARCHIVE_MATCH_CTIME: u32 = 512;
pub const ARCHIVE_MATCH_NEWER: u32 = 1;
pub const ARCHIVE_MATCH_OLDER: u32 = 2;
pub const ARCHIVE_MATCH_EQUAL: u32 = 16;
pub const AE_SYMLINK_TYPE_UNDEFINED: u32 = 0;
pub const AE_SYMLINK_TYPE_FILE: u32 = 1;
pub const AE_SYMLINK_TYPE_DIRECTORY: u32 = 2;
pub const ARCHIVE_ENTRY_DIGEST_MD5: u32 = 1;
pub const ARCHIVE_ENTRY_DIGEST_RMD160: u32 = 2;
pub const ARCHIVE_ENTRY_DIGEST_SHA1: u32 = 3;
pub const ARCHIVE_ENTRY_DIGEST_SHA256: u32 = 4;
pub const ARCHIVE_ENTRY_DIGEST_SHA384: u32 = 5;
pub const ARCHIVE_ENTRY_DIGEST_SHA512: u32 = 6;
pub const ARCHIVE_ENTRY_ACL_EXECUTE: u32 = 1;
pub const ARCHIVE_ENTRY_ACL_WRITE: u32 = 2;
pub const ARCHIVE_ENTRY_ACL_READ: u32 = 4;
pub const ARCHIVE_ENTRY_ACL_READ_DATA: u32 = 8;
pub const ARCHIVE_ENTRY_ACL_LIST_DIRECTORY: u32 = 8;
pub const ARCHIVE_ENTRY_ACL_WRITE_DATA: u32 = 16;
pub const ARCHIVE_ENTRY_ACL_ADD_FILE: u32 = 16;
pub const ARCHIVE_ENTRY_ACL_APPEND_DATA: u32 = 32;
pub const ARCHIVE_ENTRY_ACL_ADD_SUBDIRECTORY: u32 = 32;
pub const ARCHIVE_ENTRY_ACL_READ_NAMED_ATTRS: u32 = 64;
pub const ARCHIVE_ENTRY_ACL_WRITE_NAMED_ATTRS: u32 = 128;
pub const ARCHIVE_ENTRY_ACL_DELETE_CHILD: u32 = 256;
pub const ARCHIVE_ENTRY_ACL_READ_ATTRIBUTES: u32 = 512;
pub const ARCHIVE_ENTRY_ACL_WRITE_ATTRIBUTES: u32 = 1024;
pub const ARCHIVE_ENTRY_ACL_DELETE: u32 = 2048;
pub const ARCHIVE_ENTRY_ACL_READ_ACL: u32 = 4096;
pub const ARCHIVE_ENTRY_ACL_WRITE_ACL: u32 = 8192;
pub const ARCHIVE_ENTRY_ACL_WRITE_OWNER: u32 = 16384;
pub const ARCHIVE_ENTRY_ACL_SYNCHRONIZE: u32 = 32768;
pub const ARCHIVE_ENTRY_ACL_PERMS_POSIX1E: u32 = 7;
pub const ARCHIVE_ENTRY_ACL_PERMS_NFS4: u32 = 65529;
pub const ARCHIVE_ENTRY_ACL_ENTRY_INHERITED: u32 = 16777216;
pub const ARCHIVE_ENTRY_ACL_ENTRY_FILE_INHERIT: u32 = 33554432;
pub const ARCHIVE_ENTRY_ACL_ENTRY_DIRECTORY_INHERIT: u32 = 67108864;
pub const ARCHIVE_ENTRY_ACL_ENTRY_NO_PROPAGATE_INHERIT: u32 = 134217728;
pub const ARCHIVE_ENTRY_ACL_ENTRY_INHERIT_ONLY: u32 = 268435456;
pub const ARCHIVE_ENTRY_ACL_ENTRY_SUCCESSFUL_ACCESS: u32 = 536870912;
pub const ARCHIVE_ENTRY_ACL_ENTRY_FAILED_ACCESS: u32 = 1073741824;
pub const ARCHIVE_ENTRY_ACL_INHERITANCE_NFS4: u32 = 2130706432;
pub const ARCHIVE_ENTRY_ACL_TYPE_ACCESS: u32 = 256;
pub const ARCHIVE_ENTRY_ACL_TYPE_DEFAULT: u32 = 512;
pub const ARCHIVE_ENTRY_ACL_TYPE_ALLOW: u32 = 1024;
pub const ARCHIVE_ENTRY_ACL_TYPE_DENY: u32 = 2048;
pub const ARCHIVE_ENTRY_ACL_TYPE_AUDIT: u32 = 4096;
pub const ARCHIVE_ENTRY_ACL_TYPE_ALARM: u32 = 8192;
pub const ARCHIVE_ENTRY_ACL_TYPE_POSIX1E: u32 = 768;
pub const ARCHIVE_ENTRY_ACL_TYPE_NFS4: u32 = 15360;
pub const ARCHIVE_ENTRY_ACL_USER: u32 = 10001;
pub const ARCHIVE_ENTRY_ACL_USER_OBJ: u32 = 10002;
pub const ARCHIVE_ENTRY_ACL_GROUP: u32 = 10003;
pub const ARCHIVE_ENTRY_ACL_GROUP_OBJ: u32 = 10004;
pub const ARCHIVE_ENTRY_ACL_MASK: u32 = 10005;
pub const ARCHIVE_ENTRY_ACL_OTHER: u32 = 10006;
pub const ARCHIVE_ENTRY_ACL_EVERYONE: u32 = 10107;
pub const ARCHIVE_ENTRY_ACL_STYLE_EXTRA_ID: u32 = 1;
pub const ARCHIVE_ENTRY_ACL_STYLE_MARK_DEFAULT: u32 = 2;
pub const ARCHIVE_ENTRY_ACL_STYLE_SOLARIS: u32 = 4;
pub const ARCHIVE_ENTRY_ACL_STYLE_SEPARATOR_COMMA: u32 = 8;
pub const ARCHIVE_ENTRY_ACL_STYLE_COMPACT: u32 = 16;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_uint;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __time_t = ::std::os::raw::c_long;
pub type __blksize_t = ::std::os::raw::c_int;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type time_t = __time_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timespec {
    pub tv_sec: __time_t,
    pub tv_nsec: __syscall_slong_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of timespec"][::std::mem::size_of::<timespec>() - 16usize];
    ["Alignment of timespec"][::std::mem::align_of::<timespec>() - 8usize];
    ["Offset of field: timespec::tv_sec"][::std::mem::offset_of!(timespec, tv_sec) - 0usize];
    ["Offset of field: timespec::tv_nsec"][::std::mem::offset_of!(timespec, tv_nsec) - 8usize];
};
pub type dev_t = __dev_t;
pub type mode_t = __mode_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct stat {
    pub st_dev: __dev_t,
    pub st_ino: __ino_t,
    pub st_mode: __mode_t,
    pub st_nlink: __nlink_t,
    pub st_uid: __uid_t,
    pub st_gid: __gid_t,
    pub st_rdev: __dev_t,
    pub __pad1: __dev_t,
    pub st_size: __off_t,
    pub st_blksize: __blksize_t,
    pub __pad2: ::std::os::raw::c_int,
    pub st_blocks: __blkcnt_t,
    pub st_atim: timespec,
    pub st_mtim: timespec,
    pub st_ctim: timespec,
    pub __glibc_reserved: [::std::os::raw::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of stat"][::std::mem::size_of::<stat>() - 128usize];
    ["Alignment of stat"][::std::mem::align_of::<stat>() - 8usize];
    ["Offset of field: stat::st_dev"][::std::mem::offset_of!(stat, st_dev) - 0usize];
    ["Offset of field: stat::st_ino"][::std::mem::offset_of!(stat, st_ino) - 8usize];
    ["Offset of field: stat::st_mode"][::std::mem::offset_of!(stat, st_mode) - 16usize];
    ["Offset of field: stat::st_nlink"][::std::mem::offset_of!(stat, st_nlink) - 20usize];
    ["Offset of field: stat::st_uid"][::std::mem::offset_of!(stat, st_uid) - 24usize];
    ["Offset of field: stat::st_gid"][::std::mem::offset_of!(stat, st_gid) - 28usize];
    ["Offset of field: stat::st_rdev"][::std::mem::offset_of!(stat, st_rdev) - 32usize];
    ["Offset of field: stat::__pad1"][::std::mem::offset_of!(stat, __pad1) - 40usize];
    ["Offset of field: stat::st_size"][::std::mem::offset_of!(stat, st_size) - 48usize];
    ["Offset of field: stat::st_blksize"][::std::mem::offset_of!(stat, st_blksize) - 56usize];
    ["Offset of field: stat::__pad2"][::std::mem::offset_of!(stat, __pad2) - 60usize];
    ["Offset of field: stat::st_blocks"][::std::mem::offset_of!(stat, st_blocks) - 64usize];
    ["Offset of field: stat::st_atim"][::std::mem::offset_of!(stat, st_atim) - 72usize];
    ["Offset of field: stat::st_mtim"][::std::mem::offset_of!(stat, st_mtim) - 88usize];
    ["Offset of field: stat::st_ctim"][::std::mem::offset_of!(stat, st_ctim) - 104usize];
    ["Offset of field: stat::__glibc_reserved"][::std::mem::offset_of!(stat, __glibc_reserved) - 120usize];
};
pub type wchar_t = ::std::os::raw::c_uint;
pub type FILE = _IO_FILE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_marker {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_codecvt {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_wide_data {
    _unused: [u8; 0],
}
pub type _IO_lock_t = ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_FILE {
    pub _flags: ::std::os::raw::c_int,
    pub _IO_read_ptr: *mut ::std::os::raw::c_char,
    pub _IO_read_end: *mut ::std::os::raw::c_char,
    pub _IO_read_base: *mut ::std::os::raw::c_char,
    pub _IO_write_base: *mut ::std::os::raw::c_char,
    pub _IO_write_ptr: *mut ::std::os::raw::c_char,
    pub _IO_write_end: *mut ::std::os::raw::c_char,
    pub _IO_buf_base: *mut ::std::os::raw::c_char,
    pub _IO_buf_end: *mut ::std::os::raw::c_char,
    pub _IO_save_base: *mut ::std::os::raw::c_char,
    pub _IO_backup_base: *mut ::std::os::raw::c_char,
    pub _IO_save_end: *mut ::std::os::raw::c_char,
    pub _markers: *mut _IO_marker,
    pub _chain: *mut _IO_FILE,
    pub _fileno: ::std::os::raw::c_int,
    pub _bitfield_align_1: [u32; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 3usize]>,
    pub _short_backupbuf: [::std::os::raw::c_char; 1usize],
    pub _old_offset: __off_t,
    pub _cur_column: ::std::os::raw::c_ushort,
    pub _vtable_offset: ::std::os::raw::c_schar,
    pub _shortbuf: [::std::os::raw::c_char; 1usize],
    pub _lock: *mut _IO_lock_t,
    pub _offset: __off64_t,
    pub _codecvt: *mut _IO_codecvt,
    pub _wide_data: *mut _IO_wide_data,
    pub _freeres_list: *mut _IO_FILE,
    pub _freeres_buf: *mut ::std::os::raw::c_void,
    pub _prevchain: *mut *mut _IO_FILE,
    pub _mode: ::std::os::raw::c_int,
    pub _unused2: [::std::os::raw::c_char; 20usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _IO_FILE"][::std::mem::size_of::<_IO_FILE>() - 216usize];
    ["Alignment of _IO_FILE"][::std::mem::align_of::<_IO_FILE>() - 8usize];
    ["Offset of field: _IO_FILE::_flags"][::std::mem::offset_of!(_IO_FILE, _flags) - 0usize];
    ["Offset of field: _IO_FILE::_IO_read_ptr"][::std::mem::offset_of!(_IO_FILE, _IO_read_ptr) - 8usize];
    ["Offset of field: _IO_FILE::_IO_read_end"][::std::mem::offset_of!(_IO_FILE, _IO_read_end) - 16usize];
    ["Offset of field: _IO_FILE::_IO_read_base"][::std::mem::offset_of!(_IO_FILE, _IO_read_base) - 24usize];
    ["Offset of field: _IO_FILE::_IO_write_base"][::std::mem::offset_of!(_IO_FILE, _IO_write_base) - 32usize];
    ["Offset of field: _IO_FILE::_IO_write_ptr"][::std::mem::offset_of!(_IO_FILE, _IO_write_ptr) - 40usize];
    ["Offset of field: _IO_FILE::_IO_write_end"][::std::mem::offset_of!(_IO_FILE, _IO_write_end) - 48usize];
    ["Offset of field: _IO_FILE::_IO_buf_base"][::std::mem::offset_of!(_IO_FILE, _IO_buf_base) - 56usize];
    ["Offset of field: _IO_FILE::_IO_buf_end"][::std::mem::offset_of!(_IO_FILE, _IO_buf_end) - 64usize];
    ["Offset of field: _IO_FILE::_IO_save_base"][::std::mem::offset_of!(_IO_FILE, _IO_save_base) - 72usize];
    ["Offset of field: _IO_FILE::_IO_backup_base"][::std::mem::offset_of!(_IO_FILE, _IO_backup_base) - 80usize];
    ["Offset of field: _IO_FILE::_IO_save_end"][::std::mem::offset_of!(_IO_FILE, _IO_save_end) - 88usize];
    ["Offset of field: _IO_FILE::_markers"][::std::mem::offset_of!(_IO_FILE, _markers) - 96usize];
    ["Offset of field: _IO_FILE::_chain"][::std::mem::offset_of!(_IO_FILE, _chain) - 104usize];
    ["Offset of field: _IO_FILE::_fileno"][::std::mem::offset_of!(_IO_FILE, _fileno) - 112usize];
    ["Offset of field: _IO_FILE::_short_backupbuf"][::std::mem::offset_of!(_IO_FILE, _short_backupbuf) - 119usize];
    ["Offset of field: _IO_FILE::_old_offset"][::std::mem::offset_of!(_IO_FILE, _old_offset) - 120usize];
    ["Offset of field: _IO_FILE::_cur_column"][::std::mem::offset_of!(_IO_FILE, _cur_column) - 128usize];
    ["Offset of field: _IO_FILE::_vtable_offset"][::std::mem::offset_of!(_IO_FILE, _vtable_offset) - 130usize];
    ["Offset of field: _IO_FILE::_shortbuf"][::std::mem::offset_of!(_IO_FILE, _shortbuf) - 131usize];
    ["Offset of field: _IO_FILE::_lock"][::std::mem::offset_of!(_IO_FILE, _lock) - 136usize];
    ["Offset of field: _IO_FILE::_offset"][::std::mem::offset_of!(_IO_FILE, _offset) - 144usize];
    ["Offset of field: _IO_FILE::_codecvt"][::std::mem::offset_of!(_IO_FILE, _codecvt) - 152usize];
    ["Offset of field: _IO_FILE::_wide_data"][::std::mem::offset_of!(_IO_FILE, _wide_data) - 160usize];
    ["Offset of field: _IO_FILE::_freeres_list"][::std::mem::offset_of!(_IO_FILE, _freeres_list) - 168usize];
    ["Offset of field: _IO_FILE::_freeres_buf"][::std::mem::offset_of!(_IO_FILE, _freeres_buf) - 176usize];
    ["Offset of field: _IO_FILE::_prevchain"][::std::mem::offset_of!(_IO_FILE, _prevchain) - 184usize];
    ["Offset of field: _IO_FILE::_mode"][::std::mem::offset_of!(_IO_FILE, _mode) - 192usize];
    ["Offset of field: _IO_FILE::_unused2"][::std::mem::offset_of!(_IO_FILE, _unused2) - 196usize];
};
impl _IO_FILE {
    #[inline]
    pub fn _flags2(&self) -> ::std::os::raw::c_int {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 24u8) as u32) }
    }
    #[inline]
    pub fn set__flags2(&mut self, val: ::std::os::raw::c_int) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 24u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(_flags2: ::std::os::raw::c_int) -> __BindgenBitfieldUnit<[u8; 3usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 3usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 24u8, {
            let _flags2: u32 = unsafe { ::std::mem::transmute(_flags2) };
            _flags2 as u64
        });
        __bindgen_bitfield_unit
    }
}
pub type la_int64_t = i64;
pub type la_uint64_t = u64;
pub type la_ssize_t = isize;
extern "C" {
    pub fn archive_version_number() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_version_string() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_version_details() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_zlib_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_liblzma_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_bzlib_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_liblz4_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_libzstd_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_liblzo2_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_libexpat_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_libbsdxml_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_libxml2_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_mbedtls_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_nettle_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_openssl_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_libmd_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_commoncrypto_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_cng_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_wincrypt_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_librichacl_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_libacl_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_libattr_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_libiconv_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_libpcre_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_libpcre2_version() -> *const ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct archive {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct archive_entry {
    _unused: [u8; 0],
}
pub type archive_read_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
        _buffer: *mut *const ::std::os::raw::c_void,
    ) -> la_ssize_t,
>;
pub type archive_skip_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
        request: la_int64_t,
    ) -> la_int64_t,
>;
pub type archive_seek_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
        offset: la_int64_t,
        whence: ::std::os::raw::c_int,
    ) -> la_int64_t,
>;
pub type archive_write_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
        _buffer: *const ::std::os::raw::c_void,
        _length: usize,
    ) -> la_ssize_t,
>;
pub type archive_open_callback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *mut archive, _client_data: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
>;
pub type archive_close_callback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *mut archive, _client_data: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
>;
pub type archive_free_callback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *mut archive, _client_data: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
>;
pub type archive_switch_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data1: *mut ::std::os::raw::c_void,
        _client_data2: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type archive_passphrase_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
    ) -> *const ::std::os::raw::c_char,
>;
extern "C" {
    pub fn archive_read_new() -> *mut archive;
}
extern "C" {
    pub fn archive_read_support_compression_all(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_compression_bzip2(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_compression_compress(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_compression_gzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_compression_lzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_compression_lzma(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_compression_none(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_compression_program(
        arg1: *mut archive,
        command: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_compression_program_signature(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_void,
        arg4: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_compression_rpm(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_compression_uu(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_compression_xz(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_all(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_by_code(
        arg1: *mut archive,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_bzip2(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_compress(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_gzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_grzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_lrzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_lz4(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_lzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_lzma(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_lzop(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_none(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_program(
        arg1: *mut archive,
        command: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_program_signature(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_void,
        arg4: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_rpm(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_uu(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_xz(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_filter_zstd(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_7zip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_all(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_ar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_by_code(
        arg1: *mut archive,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_cab(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_cpio(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_empty(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_gnutar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_iso9660(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_lha(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_mtree(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_rar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_rar5(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_raw(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_tar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_warc(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_xar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_zip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_zip_streamable(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_support_format_zip_seekable(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_set_format(arg1: *mut archive, arg2: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_append_filter(arg1: *mut archive, arg2: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_append_filter_program(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_append_filter_program_signature(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_void,
        arg4: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_set_open_callback(arg1: *mut archive, arg2: archive_open_callback) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_set_read_callback(arg1: *mut archive, arg2: archive_read_callback) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_set_seek_callback(arg1: *mut archive, arg2: archive_seek_callback) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_set_skip_callback(arg1: *mut archive, arg2: archive_skip_callback) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_set_close_callback(arg1: *mut archive, arg2: archive_close_callback) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_set_switch_callback(arg1: *mut archive, arg2: archive_switch_callback)
        -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_set_callback_data(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_set_callback_data2(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_add_callback_data(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_append_callback_data(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_prepend_callback_data(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_open1(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_open(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
        arg2: archive_open_callback,
        arg3: archive_read_callback,
        arg4: archive_close_callback,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_open2(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
        arg2: archive_open_callback,
        arg3: archive_read_callback,
        arg4: archive_skip_callback,
        arg5: archive_close_callback,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_open_filename(
        arg1: *mut archive,
        _filename: *const ::std::os::raw::c_char,
        _block_size: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_open_filenames(
        arg1: *mut archive,
        _filenames: *mut *const ::std::os::raw::c_char,
        _block_size: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_open_filename_w(
        arg1: *mut archive,
        _filename: *const wchar_t,
        _block_size: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_open_file(
        arg1: *mut archive,
        _filename: *const ::std::os::raw::c_char,
        _block_size: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_open_memory(
        arg1: *mut archive,
        buff: *const ::std::os::raw::c_void,
        size: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_open_memory2(
        a: *mut archive,
        buff: *const ::std::os::raw::c_void,
        size: usize,
        read_size: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_open_fd(
        arg1: *mut archive,
        _fd: ::std::os::raw::c_int,
        _block_size: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_open_FILE(arg1: *mut archive, _file: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_next_header(arg1: *mut archive, arg2: *mut *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_next_header2(arg1: *mut archive, arg2: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_header_position(arg1: *mut archive) -> la_int64_t;
}
extern "C" {
    pub fn archive_read_has_encrypted_entries(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_format_capabilities(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_data(arg1: *mut archive, arg2: *mut ::std::os::raw::c_void, arg3: usize) -> la_ssize_t;
}
extern "C" {
    pub fn archive_seek_data(arg1: *mut archive, arg2: la_int64_t, arg3: ::std::os::raw::c_int) -> la_int64_t;
}
extern "C" {
    pub fn archive_read_data_block(
        a: *mut archive,
        buff: *mut *const ::std::os::raw::c_void,
        size: *mut usize,
        offset: *mut la_int64_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_data_skip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_data_into_fd(arg1: *mut archive, fd: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_set_format_option(
        _a: *mut archive,
        m: *const ::std::os::raw::c_char,
        o: *const ::std::os::raw::c_char,
        v: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_set_filter_option(
        _a: *mut archive,
        m: *const ::std::os::raw::c_char,
        o: *const ::std::os::raw::c_char,
        v: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_set_option(
        _a: *mut archive,
        m: *const ::std::os::raw::c_char,
        o: *const ::std::os::raw::c_char,
        v: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_set_options(_a: *mut archive, opts: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_add_passphrase(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_set_passphrase_callback(
        arg1: *mut archive,
        client_data: *mut ::std::os::raw::c_void,
        arg2: archive_passphrase_callback,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_extract(
        arg1: *mut archive,
        arg2: *mut archive_entry,
        flags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_extract2(
        arg1: *mut archive,
        arg2: *mut archive_entry,
        arg3: *mut archive,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_extract_set_progress_callback(
        arg1: *mut archive,
        _progress_func: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
        _user_data: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn archive_read_extract_set_skip_file(arg1: *mut archive, arg2: la_int64_t, arg3: la_int64_t);
}
extern "C" {
    pub fn archive_read_close(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_free(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_finish(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_new() -> *mut archive;
}
extern "C" {
    pub fn archive_write_set_bytes_per_block(
        arg1: *mut archive,
        bytes_per_block: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_get_bytes_per_block(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_bytes_in_last_block(
        arg1: *mut archive,
        bytes_in_last_block: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_get_bytes_in_last_block(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_skip_file(arg1: *mut archive, arg2: la_int64_t, arg3: la_int64_t)
        -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_compression_bzip2(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_compression_compress(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_compression_gzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_compression_lzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_compression_lzma(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_compression_none(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_compression_program(
        arg1: *mut archive,
        cmd: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_compression_xz(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter(arg1: *mut archive, filter_code: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_by_name(
        arg1: *mut archive,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_b64encode(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_bzip2(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_compress(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_grzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_gzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_lrzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_lz4(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_lzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_lzma(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_lzop(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_none(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_program(
        arg1: *mut archive,
        cmd: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_uuencode(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_xz(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_add_filter_zstd(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format(arg1: *mut archive, format_code: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_by_name(
        arg1: *mut archive,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_7zip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_ar_bsd(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_ar_svr4(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_cpio(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_cpio_bin(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_cpio_newc(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_cpio_odc(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_cpio_pwb(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_gnutar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_iso9660(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_mtree(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_mtree_classic(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_pax(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_pax_restricted(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_raw(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_shar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_shar_dump(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_ustar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_v7tar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_warc(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_xar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_zip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_filter_by_ext(
        a: *mut archive,
        filename: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_filter_by_ext_def(
        a: *mut archive,
        filename: *const ::std::os::raw::c_char,
        def_ext: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_zip_set_compression_deflate(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_zip_set_compression_store(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_zip_set_compression_lzma(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_zip_set_compression_xz(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_zip_set_compression_bzip2(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_zip_set_compression_zstd(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_open(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: archive_open_callback,
        arg4: archive_write_callback,
        arg5: archive_close_callback,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_open2(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: archive_open_callback,
        arg4: archive_write_callback,
        arg5: archive_close_callback,
        arg6: archive_free_callback,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_open_fd(arg1: *mut archive, _fd: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_open_filename(
        arg1: *mut archive,
        _file: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_open_filename_w(arg1: *mut archive, _file: *const wchar_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_open_file(arg1: *mut archive, _file: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_open_FILE(arg1: *mut archive, arg2: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_open_memory(
        arg1: *mut archive,
        _buffer: *mut ::std::os::raw::c_void,
        _buffSize: usize,
        _used: *mut usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_header(arg1: *mut archive, arg2: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_data(arg1: *mut archive, arg2: *const ::std::os::raw::c_void, arg3: usize) -> la_ssize_t;
}
extern "C" {
    pub fn archive_write_data_block(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_void,
        arg3: usize,
        arg4: la_int64_t,
    ) -> la_ssize_t;
}
extern "C" {
    pub fn archive_write_finish_entry(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_close(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_fail(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_free(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_finish(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_format_option(
        _a: *mut archive,
        m: *const ::std::os::raw::c_char,
        o: *const ::std::os::raw::c_char,
        v: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_filter_option(
        _a: *mut archive,
        m: *const ::std::os::raw::c_char,
        o: *const ::std::os::raw::c_char,
        v: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_option(
        _a: *mut archive,
        m: *const ::std::os::raw::c_char,
        o: *const ::std::os::raw::c_char,
        v: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_options(_a: *mut archive, opts: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_passphrase(_a: *mut archive, p: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_set_passphrase_callback(
        arg1: *mut archive,
        client_data: *mut ::std::os::raw::c_void,
        arg2: archive_passphrase_callback,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_disk_new() -> *mut archive;
}
extern "C" {
    pub fn archive_write_disk_set_skip_file(
        arg1: *mut archive,
        arg2: la_int64_t,
        arg3: la_int64_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_disk_set_options(arg1: *mut archive, flags: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_disk_set_standard_lookup(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_disk_set_group_lookup(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut ::std::os::raw::c_void,
                arg2: *const ::std::os::raw::c_char,
                arg3: la_int64_t,
            ) -> la_int64_t,
        >,
        arg4: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_disk_set_user_lookup(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut ::std::os::raw::c_void,
                arg2: *const ::std::os::raw::c_char,
                arg3: la_int64_t,
            ) -> la_int64_t,
        >,
        arg4: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_write_disk_gid(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
        arg3: la_int64_t,
    ) -> la_int64_t;
}
extern "C" {
    pub fn archive_write_disk_uid(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
        arg3: la_int64_t,
    ) -> la_int64_t;
}
extern "C" {
    pub fn archive_read_disk_new() -> *mut archive;
}
extern "C" {
    pub fn archive_read_disk_set_symlink_logical(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_set_symlink_physical(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_set_symlink_hybrid(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_entry_from_file(
        arg1: *mut archive,
        arg2: *mut archive_entry,
        arg3: ::std::os::raw::c_int,
        arg4: *const stat,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_gname(arg1: *mut archive, arg2: la_int64_t) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_read_disk_uname(arg1: *mut archive, arg2: la_int64_t) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_read_disk_set_standard_lookup(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_set_gname_lookup(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<
            unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void, arg2: la_int64_t) -> *const ::std::os::raw::c_char,
        >,
        arg4: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_set_uname_lookup(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<
            unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void, arg2: la_int64_t) -> *const ::std::os::raw::c_char,
        >,
        arg4: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_open(arg1: *mut archive, arg2: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_open_w(arg1: *mut archive, arg2: *const wchar_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_descend(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_can_descend(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_current_filesystem(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_current_filesystem_is_synthetic(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_current_filesystem_is_remote(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_set_atime_restored(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_set_behavior(arg1: *mut archive, flags: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_set_matching(
        arg1: *mut archive,
        _matching: *mut archive,
        _excluded_func: ::std::option::Option<
            unsafe extern "C" fn(arg1: *mut archive, arg2: *mut ::std::os::raw::c_void, arg3: *mut archive_entry),
        >,
        _client_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_read_disk_set_metadata_filter_callback(
        arg1: *mut archive,
        _metadata_filter_func: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut archive,
                arg2: *mut ::std::os::raw::c_void,
                arg3: *mut archive_entry,
            ) -> ::std::os::raw::c_int,
        >,
        _client_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_free(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_filter_count(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_filter_bytes(arg1: *mut archive, arg2: ::std::os::raw::c_int) -> la_int64_t;
}
extern "C" {
    pub fn archive_filter_code(arg1: *mut archive, arg2: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_filter_name(arg1: *mut archive, arg2: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_position_compressed(arg1: *mut archive) -> la_int64_t;
}
extern "C" {
    pub fn archive_position_uncompressed(arg1: *mut archive) -> la_int64_t;
}
extern "C" {
    pub fn archive_compression_name(arg1: *mut archive) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_compression(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_parse_date(now: time_t, datestr: *const ::std::os::raw::c_char) -> time_t;
}
extern "C" {
    pub fn archive_errno(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_error_string(arg1: *mut archive) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_format_name(arg1: *mut archive) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_format(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_clear_error(arg1: *mut archive);
}
extern "C" {
    pub fn archive_set_error(arg1: *mut archive, _err: ::std::os::raw::c_int, fmt: *const ::std::os::raw::c_char, ...);
}
extern "C" {
    pub fn archive_copy_error(dest: *mut archive, src: *mut archive);
}
extern "C" {
    pub fn archive_file_count(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_new() -> *mut archive;
}
extern "C" {
    pub fn archive_match_free(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_excluded(arg1: *mut archive, arg2: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_path_excluded(arg1: *mut archive, arg2: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_set_inclusion_recursion(
        arg1: *mut archive,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_exclude_pattern(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_exclude_pattern_w(arg1: *mut archive, arg2: *const wchar_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_exclude_pattern_from_file(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
        _nullSeparator: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_exclude_pattern_from_file_w(
        arg1: *mut archive,
        arg2: *const wchar_t,
        _nullSeparator: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_pattern(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_pattern_w(arg1: *mut archive, arg2: *const wchar_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_pattern_from_file(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
        _nullSeparator: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_pattern_from_file_w(
        arg1: *mut archive,
        arg2: *const wchar_t,
        _nullSeparator: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_path_unmatched_inclusions(arg1: *mut archive) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_path_unmatched_inclusions_next(
        arg1: *mut archive,
        arg2: *mut *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_path_unmatched_inclusions_next_w(
        arg1: *mut archive,
        arg2: *mut *const wchar_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_time_excluded(arg1: *mut archive, arg2: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_time(
        arg1: *mut archive,
        _flag: ::std::os::raw::c_int,
        _sec: time_t,
        _nsec: ::std::os::raw::c_long,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_date(
        arg1: *mut archive,
        _flag: ::std::os::raw::c_int,
        _datestr: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_date_w(
        arg1: *mut archive,
        _flag: ::std::os::raw::c_int,
        _datestr: *const wchar_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_file_time(
        arg1: *mut archive,
        _flag: ::std::os::raw::c_int,
        _pathname: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_file_time_w(
        arg1: *mut archive,
        _flag: ::std::os::raw::c_int,
        _pathname: *const wchar_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_exclude_entry(
        arg1: *mut archive,
        _flag: ::std::os::raw::c_int,
        arg2: *mut archive_entry,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_owner_excluded(arg1: *mut archive, arg2: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_uid(arg1: *mut archive, arg2: la_int64_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_gid(arg1: *mut archive, arg2: la_int64_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_uname(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_uname_w(arg1: *mut archive, arg2: *const wchar_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_gname(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_match_include_gname_w(arg1: *mut archive, arg2: *const wchar_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_utility_string_sort(arg1: *mut *mut ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_clear(arg1: *mut archive_entry) -> *mut archive_entry;
}
extern "C" {
    pub fn archive_entry_clone(arg1: *mut archive_entry) -> *mut archive_entry;
}
extern "C" {
    pub fn archive_entry_free(arg1: *mut archive_entry);
}
extern "C" {
    pub fn archive_entry_new() -> *mut archive_entry;
}
extern "C" {
    pub fn archive_entry_new2(arg1: *mut archive) -> *mut archive_entry;
}
extern "C" {
    pub fn archive_entry_atime(arg1: *mut archive_entry) -> time_t;
}
extern "C" {
    pub fn archive_entry_atime_nsec(arg1: *mut archive_entry) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn archive_entry_atime_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_birthtime(arg1: *mut archive_entry) -> time_t;
}
extern "C" {
    pub fn archive_entry_birthtime_nsec(arg1: *mut archive_entry) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn archive_entry_birthtime_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_ctime(arg1: *mut archive_entry) -> time_t;
}
extern "C" {
    pub fn archive_entry_ctime_nsec(arg1: *mut archive_entry) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn archive_entry_ctime_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_dev(arg1: *mut archive_entry) -> dev_t;
}
extern "C" {
    pub fn archive_entry_dev_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_devmajor(arg1: *mut archive_entry) -> dev_t;
}
extern "C" {
    pub fn archive_entry_devminor(arg1: *mut archive_entry) -> dev_t;
}
extern "C" {
    pub fn archive_entry_filetype(arg1: *mut archive_entry) -> mode_t;
}
extern "C" {
    pub fn archive_entry_filetype_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_fflags(
        arg1: *mut archive_entry,
        arg2: *mut ::std::os::raw::c_ulong,
        arg3: *mut ::std::os::raw::c_ulong,
    );
}
extern "C" {
    pub fn archive_entry_fflags_text(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_gid(arg1: *mut archive_entry) -> la_int64_t;
}
extern "C" {
    pub fn archive_entry_gid_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_gname(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_gname_utf8(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_gname_w(arg1: *mut archive_entry) -> *const wchar_t;
}
extern "C" {
    pub fn archive_entry_set_link_to_hardlink(arg1: *mut archive_entry);
}
extern "C" {
    pub fn archive_entry_hardlink(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_hardlink_utf8(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_hardlink_w(arg1: *mut archive_entry) -> *const wchar_t;
}
extern "C" {
    pub fn archive_entry_hardlink_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_ino(arg1: *mut archive_entry) -> la_int64_t;
}
extern "C" {
    pub fn archive_entry_ino64(arg1: *mut archive_entry) -> la_int64_t;
}
extern "C" {
    pub fn archive_entry_ino_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_mode(arg1: *mut archive_entry) -> mode_t;
}
extern "C" {
    pub fn archive_entry_mtime(arg1: *mut archive_entry) -> time_t;
}
extern "C" {
    pub fn archive_entry_mtime_nsec(arg1: *mut archive_entry) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn archive_entry_mtime_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_nlink(arg1: *mut archive_entry) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn archive_entry_pathname(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_pathname_utf8(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_pathname_w(arg1: *mut archive_entry) -> *const wchar_t;
}
extern "C" {
    pub fn archive_entry_perm(arg1: *mut archive_entry) -> mode_t;
}
extern "C" {
    pub fn archive_entry_perm_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_rdev_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_rdev(arg1: *mut archive_entry) -> dev_t;
}
extern "C" {
    pub fn archive_entry_rdevmajor(arg1: *mut archive_entry) -> dev_t;
}
extern "C" {
    pub fn archive_entry_rdevminor(arg1: *mut archive_entry) -> dev_t;
}
extern "C" {
    pub fn archive_entry_sourcepath(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_sourcepath_w(arg1: *mut archive_entry) -> *const wchar_t;
}
extern "C" {
    pub fn archive_entry_size(arg1: *mut archive_entry) -> la_int64_t;
}
extern "C" {
    pub fn archive_entry_size_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_strmode(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_set_link_to_symlink(arg1: *mut archive_entry);
}
extern "C" {
    pub fn archive_entry_symlink(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_symlink_utf8(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_symlink_type(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_symlink_w(arg1: *mut archive_entry) -> *const wchar_t;
}
extern "C" {
    pub fn archive_entry_uid(arg1: *mut archive_entry) -> la_int64_t;
}
extern "C" {
    pub fn archive_entry_uid_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_uname(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_uname_utf8(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_uname_w(arg1: *mut archive_entry) -> *const wchar_t;
}
extern "C" {
    pub fn archive_entry_is_data_encrypted(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_is_metadata_encrypted(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_is_encrypted(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_set_atime(arg1: *mut archive_entry, arg2: time_t, arg3: ::std::os::raw::c_long);
}
extern "C" {
    pub fn archive_entry_unset_atime(arg1: *mut archive_entry);
}
extern "C" {
    pub fn archive_entry_set_birthtime(arg1: *mut archive_entry, arg2: time_t, arg3: ::std::os::raw::c_long);
}
extern "C" {
    pub fn archive_entry_unset_birthtime(arg1: *mut archive_entry);
}
extern "C" {
    pub fn archive_entry_set_ctime(arg1: *mut archive_entry, arg2: time_t, arg3: ::std::os::raw::c_long);
}
extern "C" {
    pub fn archive_entry_unset_ctime(arg1: *mut archive_entry);
}
extern "C" {
    pub fn archive_entry_set_dev(arg1: *mut archive_entry, arg2: dev_t);
}
extern "C" {
    pub fn archive_entry_set_devmajor(arg1: *mut archive_entry, arg2: dev_t);
}
extern "C" {
    pub fn archive_entry_set_devminor(arg1: *mut archive_entry, arg2: dev_t);
}
extern "C" {
    pub fn archive_entry_set_filetype(arg1: *mut archive_entry, arg2: ::std::os::raw::c_uint);
}
extern "C" {
    pub fn archive_entry_set_fflags(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_ulong,
        arg3: ::std::os::raw::c_ulong,
    );
}
extern "C" {
    pub fn archive_entry_copy_fflags_text(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_copy_fflags_text_len(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
        arg3: usize,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_copy_fflags_text_w(arg1: *mut archive_entry, arg2: *const wchar_t) -> *const wchar_t;
}
extern "C" {
    pub fn archive_entry_set_gid(arg1: *mut archive_entry, arg2: la_int64_t);
}
extern "C" {
    pub fn archive_entry_set_gname(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_set_gname_utf8(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_copy_gname(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_copy_gname_w(arg1: *mut archive_entry, arg2: *const wchar_t);
}
extern "C" {
    pub fn archive_entry_update_gname_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_set_hardlink(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_set_hardlink_utf8(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_copy_hardlink(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_copy_hardlink_w(arg1: *mut archive_entry, arg2: *const wchar_t);
}
extern "C" {
    pub fn archive_entry_update_hardlink_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_set_ino(arg1: *mut archive_entry, arg2: la_int64_t);
}
extern "C" {
    pub fn archive_entry_set_ino64(arg1: *mut archive_entry, arg2: la_int64_t);
}
extern "C" {
    pub fn archive_entry_set_link(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_set_link_utf8(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_copy_link(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_copy_link_w(arg1: *mut archive_entry, arg2: *const wchar_t);
}
extern "C" {
    pub fn archive_entry_update_link_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_set_mode(arg1: *mut archive_entry, arg2: mode_t);
}
extern "C" {
    pub fn archive_entry_set_mtime(arg1: *mut archive_entry, arg2: time_t, arg3: ::std::os::raw::c_long);
}
extern "C" {
    pub fn archive_entry_unset_mtime(arg1: *mut archive_entry);
}
extern "C" {
    pub fn archive_entry_set_nlink(arg1: *mut archive_entry, arg2: ::std::os::raw::c_uint);
}
extern "C" {
    pub fn archive_entry_set_pathname(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_set_pathname_utf8(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_copy_pathname(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_copy_pathname_w(arg1: *mut archive_entry, arg2: *const wchar_t);
}
extern "C" {
    pub fn archive_entry_update_pathname_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_set_perm(arg1: *mut archive_entry, arg2: mode_t);
}
extern "C" {
    pub fn archive_entry_set_rdev(arg1: *mut archive_entry, arg2: dev_t);
}
extern "C" {
    pub fn archive_entry_set_rdevmajor(arg1: *mut archive_entry, arg2: dev_t);
}
extern "C" {
    pub fn archive_entry_set_rdevminor(arg1: *mut archive_entry, arg2: dev_t);
}
extern "C" {
    pub fn archive_entry_set_size(arg1: *mut archive_entry, arg2: la_int64_t);
}
extern "C" {
    pub fn archive_entry_unset_size(arg1: *mut archive_entry);
}
extern "C" {
    pub fn archive_entry_copy_sourcepath(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_copy_sourcepath_w(arg1: *mut archive_entry, arg2: *const wchar_t);
}
extern "C" {
    pub fn archive_entry_set_symlink(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_set_symlink_type(arg1: *mut archive_entry, arg2: ::std::os::raw::c_int);
}
extern "C" {
    pub fn archive_entry_set_symlink_utf8(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_copy_symlink(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_copy_symlink_w(arg1: *mut archive_entry, arg2: *const wchar_t);
}
extern "C" {
    pub fn archive_entry_update_symlink_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_set_uid(arg1: *mut archive_entry, arg2: la_int64_t);
}
extern "C" {
    pub fn archive_entry_set_uname(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_set_uname_utf8(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_copy_uname(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_copy_uname_w(arg1: *mut archive_entry, arg2: *const wchar_t);
}
extern "C" {
    pub fn archive_entry_update_uname_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_set_is_data_encrypted(arg1: *mut archive_entry, is_encrypted: ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_set_is_metadata_encrypted(arg1: *mut archive_entry, is_encrypted: ::std::os::raw::c_char);
}
extern "C" {
    pub fn archive_entry_stat(arg1: *mut archive_entry) -> *const stat;
}
extern "C" {
    pub fn archive_entry_copy_stat(arg1: *mut archive_entry, arg2: *const stat);
}
extern "C" {
    pub fn archive_entry_mac_metadata(arg1: *mut archive_entry, arg2: *mut usize) -> *const ::std::os::raw::c_void;
}
extern "C" {
    pub fn archive_entry_copy_mac_metadata(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_void, arg3: usize);
}
extern "C" {
    pub fn archive_entry_digest(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn archive_entry_set_digest(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
        arg3: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_acl_clear(arg1: *mut archive_entry);
}
extern "C" {
    pub fn archive_entry_acl_add_entry(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
        arg4: ::std::os::raw::c_int,
        arg5: ::std::os::raw::c_int,
        arg6: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_acl_add_entry_w(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
        arg4: ::std::os::raw::c_int,
        arg5: ::std::os::raw::c_int,
        arg6: *const wchar_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_acl_reset(arg1: *mut archive_entry, arg2: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_acl_next(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut ::std::os::raw::c_int,
        arg6: *mut ::std::os::raw::c_int,
        arg7: *mut *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_acl_to_text_w(
        arg1: *mut archive_entry,
        arg2: *mut la_ssize_t,
        arg3: ::std::os::raw::c_int,
    ) -> *mut wchar_t;
}
extern "C" {
    pub fn archive_entry_acl_to_text(
        arg1: *mut archive_entry,
        arg2: *mut la_ssize_t,
        arg3: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_acl_from_text_w(
        arg1: *mut archive_entry,
        arg2: *const wchar_t,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_acl_from_text(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_acl_text_w(arg1: *mut archive_entry, arg2: ::std::os::raw::c_int) -> *const wchar_t;
}
extern "C" {
    pub fn archive_entry_acl_text(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn archive_entry_acl_types(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_acl_count(arg1: *mut archive_entry, arg2: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct archive_acl {
    _unused: [u8; 0],
}
extern "C" {
    pub fn archive_entry_acl(arg1: *mut archive_entry) -> *mut archive_acl;
}
extern "C" {
    pub fn archive_entry_xattr_clear(arg1: *mut archive_entry);
}
extern "C" {
    pub fn archive_entry_xattr_add_entry(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_void,
        arg4: usize,
    );
}
extern "C" {
    pub fn archive_entry_xattr_count(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_xattr_reset(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_xattr_next(
        arg1: *mut archive_entry,
        arg2: *mut *const ::std::os::raw::c_char,
        arg3: *mut *const ::std::os::raw::c_void,
        arg4: *mut usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_sparse_clear(arg1: *mut archive_entry);
}
extern "C" {
    pub fn archive_entry_sparse_add_entry(arg1: *mut archive_entry, arg2: la_int64_t, arg3: la_int64_t);
}
extern "C" {
    pub fn archive_entry_sparse_count(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_sparse_reset(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn archive_entry_sparse_next(
        arg1: *mut archive_entry,
        arg2: *mut la_int64_t,
        arg3: *mut la_int64_t,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct archive_entry_linkresolver {
    _unused: [u8; 0],
}
extern "C" {
    pub fn archive_entry_linkresolver_new() -> *mut archive_entry_linkresolver;
}
extern "C" {
    pub fn archive_entry_linkresolver_set_strategy(arg1: *mut archive_entry_linkresolver, arg2: ::std::os::raw::c_int);
}
extern "C" {
    pub fn archive_entry_linkresolver_free(arg1: *mut archive_entry_linkresolver);
}
extern "C" {
    pub fn archive_entry_linkify(
        arg1: *mut archive_entry_linkresolver,
        arg2: *mut *mut archive_entry,
        arg3: *mut *mut archive_entry,
    );
}
extern "C" {
    pub fn archive_entry_partial_links(
        res: *mut archive_entry_linkresolver,
        links: *mut ::std::os::raw::c_uint,
    ) -> *mut archive_entry;
}
