#!/usr/bin/env python3
"""Generate third-party notices for release packages."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path

WORKSPACE_NOTICE = "Generated by scripts/generate-third-party-notices.py. Do not edit release copies by hand."
RUST_LICENSE_DIR = "rust"
BUNDLED_LICENSE_DIR = "bundled"
VCPKG_LICENSE_DIR = "native/vcpkg"
COMMON_LICENSE_GLOBS = (
    "LICENSE",
    "LICENSE.*",
    "LICENCE",
    "LICENCE.*",
    "COPYING",
    "COPYING.*",
    "NOTICE",
    "NOTICE.*",
)
VCPKG_PORTS = ("zlib", "bzip2", "liblzma", "zstd", "lz4", "openssl")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--workspace",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="CLI workspace root; defaults to the parent of scripts/.",
    )
    parser.add_argument(
        "--out-notices",
        type=Path,
        default=None,
        help="Output THIRD_PARTY_NOTICES.md path.",
    )
    parser.add_argument(
        "--license-dir",
        type=Path,
        default=None,
        help="Directory where license files are copied.",
    )
    return parser.parse_args()


def run_metadata(workspace: Path) -> dict:
    output = subprocess.check_output(
        ["cargo", "metadata", "--format-version", "1", "--locked"],
        cwd=workspace,
        text=True,
        encoding="utf-8",
    )
    return json.loads(output)


def markdown_escape(value: str | None) -> str:
    if not value:
        return ""
    return value.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ")


def display_path(path: Path, notice_path: Path) -> str:
    return path.relative_to(notice_path.parent).as_posix()


def copy_file(source: Path, destination: Path) -> Path:
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)
    return destination


def package_dir_name(package: dict) -> str:
    name = package["name"].replace("/", "_")
    version = package["version"].replace("/", "_")
    return f"{name}-{version}"


def candidate_license_files(package: dict) -> list[Path]:
    manifest = Path(package["manifest_path"])
    package_root = manifest.parent
    candidates: list[Path] = []

    license_file = package.get("license_file")
    if license_file:
        candidates.append((package_root / license_file).resolve())

    for pattern in COMMON_LICENSE_GLOBS:
        candidates.extend(path.resolve() for path in package_root.glob(pattern) if path.is_file())

    unique: list[Path] = []
    seen: set[Path] = set()
    for candidate in candidates:
        if candidate.is_file() and candidate not in seen:
            unique.append(candidate)
            seen.add(candidate)
    return unique


def collect_rust_crates(metadata: dict, license_dir: Path, notice_path: Path) -> list[dict]:
    package_by_id = {package["id"]: package for package in metadata["packages"]}
    workspace_members = set(metadata["workspace_members"])
    resolved_ids = {node["id"] for node in metadata["resolve"]["nodes"]}
    crates = []

    for package_id in sorted(resolved_ids):
        if package_id in workspace_members:
            continue
        package = package_by_id[package_id]
        if not str(package.get("source", "")).startswith("registry+"):
            continue

        copied_files = []
        destination_root = license_dir / RUST_LICENSE_DIR / package_dir_name(package)
        for source in candidate_license_files(package):
            copied = copy_file(source, destination_root / source.name)
            copied_files.append(display_path(copied, notice_path))

        crates.append(
            {
                "name": package["name"],
                "version": package["version"],
                "license": package.get("license") or "See copied license files",
                "source": package.get("source") or "",
                "license_files": copied_files,
            }
        )

    crates.sort(key=lambda item: (item["name"], item["version"]))
    return crates


def collect_bundled_notices(workspace: Path, license_dir: Path, notice_path: Path) -> list[dict]:
    bundled = []
    entries = [
        {
            "name": "libarchive",
            "version": "3.8.7",
            "source": "vendor/libarchive/libarchive-3.8.7",
            "license": "BSD-2-Clause-style with file-specific exceptions; see COPYING",
            "files": [workspace / "vendor/libarchive/libarchive-3.8.7/COPYING"],
            "notes": "Built into zm for broad archive listing and extraction.",
        },
        {
            "name": "UnRAR",
            "version": "vendored",
            "source": "vendor/unrar",
            "license": "UnRAR freeware license",
            "files": [workspace / "vendor/unrar/license.txt"],
            "notes": "Used only for RAR handling; not used to create RAR archives or recreate RAR compression.",
        },
    ]

    for entry in entries:
        copied_files = []
        destination_root = license_dir / BUNDLED_LICENSE_DIR / entry["name"]
        for source in entry["files"]:
            if source.is_file():
                copied = copy_file(source, destination_root / source.name)
                copied_files.append(display_path(copied, notice_path))
        bundled.append({**entry, "license_files": copied_files})

    return bundled


def vcpkg_root() -> Path | None:
    for key in ("VCPKG_INSTALLATION_ROOT", "VCPKG_ROOT"):
        value = os.environ.get(key)
        if value:
            return Path(value)

    toolchain = os.environ.get("CMAKE_TOOLCHAIN_FILE")
    if not toolchain:
        return None
    path = Path(toolchain)
    if path.name != "vcpkg.cmake":
        return None
    try:
        return path.parents[2]
    except IndexError:
        return None


def vcpkg_triplet() -> str | None:
    return os.environ.get("VCPKG_TARGET_TRIPLET") or os.environ.get("VCPKG_DEFAULT_TRIPLET")


def collect_vcpkg_notices(license_dir: Path, notice_path: Path) -> list[dict]:
    root = vcpkg_root()
    triplet = vcpkg_triplet()
    if root is None or triplet is None:
        return []

    notices = []
    for port in VCPKG_PORTS:
        copyright_file = root / "installed" / triplet / "share" / port / "copyright"
        if not copyright_file.is_file():
            continue
        copied = copy_file(copyright_file, license_dir / VCPKG_LICENSE_DIR / port / "copyright")
        notices.append(
            {
                "name": port,
                "triplet": triplet,
                "license_files": [display_path(copied, notice_path)],
            }
        )
    return notices


def format_license_files(files: list[str]) -> str:
    if not files:
        return "Metadata only; no license file found in the local Cargo cache"
    return "<br>".join(files)


def render_notices(
    workspace: Path,
    notice_path: Path,
    rust_crates: list[dict],
    bundled: list[dict],
    vcpkg_notices: list[dict],
) -> str:
    lines = [
        "# Third-Party Notices",
        "",
        WORKSPACE_NOTICE,
        "",
        "This file is generated for release packages from Cargo metadata, vendored",
        "source license files, and native package manager license files when present.",
        "The referenced license files are shipped beside this notice under",
        "`third-party-licenses/`.",
        "",
        "## ZManager",
        "",
        "- License: Apache-2.0",
        "- License file: LICENSE",
        "- Notice file: NOTICE",
        "",
        "## Bundled Source",
        "",
    ]

    for entry in bundled:
        lines.extend(
            [
                f"### {entry['name']} {entry['version']}",
                "",
                f"- Source: `{entry['source']}`",
                f"- License: {entry['license']}",
                f"- License files: {', '.join(f'`{path}`' for path in entry['license_files'])}",
                f"- Notes: {entry['notes']}",
                "",
            ]
        )

    lines.extend(
        [
            "## Native Package Manager Licenses",
            "",
            "Windows release builds use vcpkg static-library triplets for compression",
            "and crypto libraries. When vcpkg metadata is available, this generator",
            "copies the relevant vcpkg `copyright` files into the release package.",
            "macOS and Linux runtime dependencies are documented separately in the",
            "`zm-<target>.deps.txt` files emitted by release packaging.",
            "",
        ]
    )
    if vcpkg_notices:
        lines.extend(["| Package | Triplet | License file |", "| --- | --- | --- |"])
        for notice in vcpkg_notices:
            lines.append(
                f"| {markdown_escape(notice['name'])} | {markdown_escape(notice['triplet'])} | {format_license_files(notice['license_files'])} |"
            )
        lines.append("")
    else:
        lines.extend(
            [
                "No vcpkg license files were detected in this build environment.",
                "",
            ]
        )

    lines.extend(
        [
            "## Rust Crate License Inventory",
            "",
            "This conservative inventory includes resolved third-party crates from",
            "`cargo metadata --locked`. It includes runtime and build-time crates so",
            "release reviewers can inspect the complete Cargo dependency closure.",
            "",
            "| Crate | Version | License metadata | License files |",
            "| --- | --- | --- | --- |",
        ]
    )
    for crate in rust_crates:
        lines.append(
            "| "
            + " | ".join(
                [
                    markdown_escape(crate["name"]),
                    markdown_escape(crate["version"]),
                    markdown_escape(crate["license"]),
                    format_license_files(crate["license_files"]),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Source Inputs",
            "",
            f"- Workspace: `{workspace}`",
            "- Cargo metadata command: `cargo metadata --format-version 1 --locked`",
            "- Bundled license inputs: `vendor/libarchive/libarchive-3.8.7/COPYING`,",
            "  `vendor/unrar/license.txt`",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    workspace = args.workspace.resolve()
    notice_path = (args.out_notices or workspace / "THIRD_PARTY_NOTICES.md").resolve()
    license_dir = (args.license_dir or workspace / "third-party-licenses").resolve()

    metadata = run_metadata(workspace)
    if license_dir.exists():
        shutil.rmtree(license_dir)
    license_dir.mkdir(parents=True)

    bundled = collect_bundled_notices(workspace, license_dir, notice_path)
    vcpkg_notices = collect_vcpkg_notices(license_dir, notice_path)
    rust_crates = collect_rust_crates(metadata, license_dir, notice_path)
    notice_path.parent.mkdir(parents=True, exist_ok=True)
    notice_path.write_text(
        render_notices(workspace, notice_path, rust_crates, bundled, vcpkg_notices),
        encoding="utf-8",
    )

    print(notice_path)
    print(license_dir)


if __name__ == "__main__":
    main()
