# fish completion for zm

set -l zm_commands create extract list test plan formats doctor completions help
set -l zm_help_topics create extract list test plan formats doctor completions
set -l zm_completion_shells bash zsh fish powershell

complete -c zm -f

complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -s h -l help -d "Show help"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -s V -l version -d "Show version"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -s q -l quiet -d "Reduce output"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -s v -l verbose -d "Increase diagnostics"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -l json -d "Emit JSON where supported"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -l color -xa "auto always never" -d "Control color output"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -l no-color -d "Disable color output"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -l progress -xa "auto always never" -d "Control progress output"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -l no-progress -d "Disable progress output"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -l no-password-prompt -d "Fail instead of prompting interactively"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -s c -l create -d "Create an archive"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -s x -l extract -d "Extract an archive"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -s t -l list -d "List archive contents"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -s T -l test -d "Test archive integrity"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -s f -l file -r -d "Archive file path"

complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -a create -d "Create an archive"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -a extract -d "Extract an archive"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -a list -d "List archive contents"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -a test -d "Test archive readability"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -a plan -d "Show planned archive entries"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -a formats -d "Show supported formats"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -a doctor -d "Verify the archive engine"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -a completions -d "Print shell completion scripts"
complete -c zm -n "not __fish_seen_subcommand_from $zm_commands" -a help -d "Show help for a command"

complete -c zm -n "__fish_seen_subcommand_from create" -s h -l help -d "Show help"
complete -c zm -n "__fish_seen_subcommand_from create" -s r -l recursive -d "Accept recursive directory input"
complete -c zm -n "__fish_seen_subcommand_from create" -s C -l directory -r -d "Use directory as input base"
complete -c zm -n "__fish_seen_subcommand_from create" -s @ -d "Read input paths from stdin"
complete -c zm -n "__fish_seen_subcommand_from create" -l files-from -r -d "Read input paths from file"
complete -c zm -n "__fish_seen_subcommand_from create" -l null -d "Read NUL-delimited path lists"
complete -c zm -n "__fish_seen_subcommand_from create" -l clean -d "Apply clean source exclusions"
complete -c zm -n "__fish_seen_subcommand_from create" -l no-ignore -d "Ignore .gitignore/default exclusions"
complete -c zm -n "__fish_seen_subcommand_from create" -l hidden -d "Include hidden files"
complete -c zm -n "__fish_seen_subcommand_from create" -l no-hidden -d "Exclude hidden dotfiles"
complete -c zm -n "__fish_seen_subcommand_from create" -s i -l include -r -d "Include archive paths matching glob"
complete -c zm -n "__fish_seen_subcommand_from create" -l exclude -r -d "Exclude archive paths matching glob"
complete -c zm -n "__fish_seen_subcommand_from create" -l exclude-from -r -d "Read exclude globs from file"
complete -c zm -n "__fish_seen_subcommand_from create" -l format -xa "zip tar.zst tzap 7z" -d "Override archive format"
complete -c zm -n "__fish_seen_subcommand_from create" -l method -r -d "Select compression method"
complete -c zm -n "__fish_seen_subcommand_from create" -l level -r -d "Compression level"
complete -c zm -n "__fish_seen_subcommand_from create" -s 0 -d "Store ZIP entries"
complete -c zm -n "__fish_seen_subcommand_from create" -s 1 -d "Compression preset 1"
complete -c zm -n "__fish_seen_subcommand_from create" -s 2 -d "Compression preset 2"
complete -c zm -n "__fish_seen_subcommand_from create" -s 3 -d "Compression preset 3"
complete -c zm -n "__fish_seen_subcommand_from create" -s 4 -d "Compression preset 4"
complete -c zm -n "__fish_seen_subcommand_from create" -s 5 -d "Compression preset 5"
complete -c zm -n "__fish_seen_subcommand_from create" -s 6 -d "Compression preset 6"
complete -c zm -n "__fish_seen_subcommand_from create" -s 7 -d "Compression preset 7"
complete -c zm -n "__fish_seen_subcommand_from create" -s 8 -d "Compression preset 8"
complete -c zm -n "__fish_seen_subcommand_from create" -s 9 -d "Compression preset 9"
complete -c zm -n "__fish_seen_subcommand_from create" -l store -d "Store ZIP entries without compression"
complete -c zm -n "__fish_seen_subcommand_from create" -l solid -d "Use solid 7z mode"
complete -c zm -n "__fish_seen_subcommand_from create" -l no-solid -d "Disable solid 7z mode"
complete -c zm -n "__fish_seen_subcommand_from create" -l volume-size -xa "64k 100m 500m 1g 2g 4g" -d "Split ZIP/7z output volumes"
complete -c zm -n "__fish_seen_subcommand_from create" -l signing-cert -r -d "Sign TZAP RootAuth with an X.509 cert or PEM bundle"
complete -c zm -n "__fish_seen_subcommand_from create" -l signing-private-key -r -d "Private key for --signing-cert"
complete -c zm -n "__fish_seen_subcommand_from create" -l signing-chain -r -d "Extra intermediate certificate chain for --signing-cert"
complete -c zm -n "__fish_seen_subcommand_from create" -s j -l junk-paths -d "Store basenames only"
complete -c zm -n "__fish_seen_subcommand_from create" -s y -l preserve-symlinks -d "Store symlink entries where supported"
complete -c zm -n "__fish_seen_subcommand_from create" -l follow-symlinks -d "Archive symlink target contents"
complete -c zm -n "__fish_seen_subcommand_from create" -l preserve-metadata -d "Preserve portable metadata"
complete -c zm -n "__fish_seen_subcommand_from create" -s X -l no-metadata -d "Omit portable metadata"
complete -c zm -n "__fish_seen_subcommand_from create" -s f -l file -r -d "Archive file path"
complete -c zm -n "__fish_seen_subcommand_from create" -l force -d "Replace existing output archive"
complete -c zm -n "__fish_seen_subcommand_from create" -l dry-run -d "Print planned entries without writing"
complete -c zm -n "__fish_seen_subcommand_from create" -s T -l test-after -d "Test archive after writing"
complete -c zm -n "__fish_seen_subcommand_from create" -l encrypt -d "Prompt for an archive password where supported"
complete -c zm -n "__fish_seen_subcommand_from create" -l password-stdin -d "Read one password line from stdin"

complete -c zm -n "__fish_seen_subcommand_from extract" -s h -l help -d "Show help"
complete -c zm -n "__fish_seen_subcommand_from extract" -s C -s d -l directory -r -d "Extract into directory"
complete -c zm -n "__fish_seen_subcommand_from extract" -l here -d "Extract into the current directory"
complete -c zm -n "__fish_seen_subcommand_from extract" -l overwrite -xa "never always ask rename" -d "Existing file policy"
complete -c zm -n "__fish_seen_subcommand_from extract" -s i -l include -r -d "Extract archive paths matching glob"
complete -c zm -n "__fish_seen_subcommand_from extract" -l exclude -r -d "Exclude archive paths matching glob"
complete -c zm -n "__fish_seen_subcommand_from extract" -l strip-components -r -d "Remove leading path components"
complete -c zm -n "__fish_seen_subcommand_from extract" -l to-stdout -d "Write selected regular file bytes to stdout"
complete -c zm -n "__fish_seen_subcommand_from extract" -l extract-nested -d "Expand known package payloads"
complete -c zm -n "__fish_seen_subcommand_from extract" -l password-stdin -d "Read one password line from stdin"

complete -c zm -n "__fish_seen_subcommand_from list" -s h -l help -d "Show help"
complete -c zm -n "__fish_seen_subcommand_from list" -s f -l file -r -d "Archive file path"
complete -c zm -n "__fish_seen_subcommand_from list" -s l -l long -d "Show long listing"
complete -c zm -n "__fish_seen_subcommand_from list" -l name-only -d "Print archive paths only"
complete -c zm -n "__fish_seen_subcommand_from list" -l tree -d "Print a hierarchical tree"
complete -c zm -n "__fish_seen_subcommand_from list" -s i -l include -r -d "List archive paths matching glob"
complete -c zm -n "__fish_seen_subcommand_from list" -l exclude -r -d "Exclude archive paths matching glob"
complete -c zm -n "__fish_seen_subcommand_from list" -l password-stdin -d "Read one password line from stdin"
complete -c zm -n "__fish_seen_subcommand_from list" -l json -d "Emit machine-readable JSON"

complete -c zm -n "__fish_seen_subcommand_from test" -s h -l help -d "Show help"
complete -c zm -n "__fish_seen_subcommand_from test" -s f -l file -r -d "Archive file path"
complete -c zm -n "__fish_seen_subcommand_from test" -s i -l include -r -d "Test archive paths matching glob"
complete -c zm -n "__fish_seen_subcommand_from test" -l exclude -r -d "Exclude archive paths matching glob"
complete -c zm -n "__fish_seen_subcommand_from test" -l password-stdin -d "Read one password line from stdin"
complete -c zm -n "__fish_seen_subcommand_from test" -l public-no-key -d "Verify TZAP X.509 RootAuth without the archive key"
complete -c zm -n "__fish_seen_subcommand_from test" -l trusted-ca-cert -r -d "Trusted CA certificate for TZAP X.509 RootAuth"
complete -c zm -n "__fish_seen_subcommand_from test" -l trusted-system-roots -d "Use system trust roots for TZAP X.509 RootAuth"
complete -c zm -n "__fish_seen_subcommand_from test" -l json -d "Emit machine-readable JSON"

complete -c zm -n "__fish_seen_subcommand_from plan" -s h -l help -d "Show help"
complete -c zm -n "__fish_seen_subcommand_from plan" -l format -xa "zip tar.zst tzap 7z" -d "Plan for a specific archive format"
complete -c zm -n "__fish_seen_subcommand_from plan" -s C -l directory -r -d "Use directory as input base"
complete -c zm -n "__fish_seen_subcommand_from plan" -s @ -d "Read input paths from stdin"
complete -c zm -n "__fish_seen_subcommand_from plan" -l files-from -r -d "Read input paths from file"
complete -c zm -n "__fish_seen_subcommand_from plan" -l null -d "Read NUL-delimited path lists"
complete -c zm -n "__fish_seen_subcommand_from plan" -l clean -d "Apply clean source exclusions"
complete -c zm -n "__fish_seen_subcommand_from plan" -l no-ignore -d "Ignore .gitignore/default exclusions"
complete -c zm -n "__fish_seen_subcommand_from plan" -s i -l include -r -d "Include archive paths matching glob"
complete -c zm -n "__fish_seen_subcommand_from plan" -l exclude -r -d "Exclude archive paths matching glob"
complete -c zm -n "__fish_seen_subcommand_from plan" -l exclude-from -r -d "Read exclude globs from file"
complete -c zm -n "__fish_seen_subcommand_from plan" -l json -d "Emit machine-readable JSON"

complete -c zm -n "__fish_seen_subcommand_from formats doctor" -s h -l help -d "Show help"
complete -c zm -n "__fish_seen_subcommand_from formats doctor" -l json -d "Emit JSON"
complete -c zm -n "__fish_seen_subcommand_from completions" -s h -l help -d "Show help"
complete -c zm -n "__fish_seen_subcommand_from completions" -a "$zm_completion_shells" -d "Completion shell"
complete -c zm -n "__fish_seen_subcommand_from help" -a "$zm_help_topics"
